/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplorerRouteImport } from './routes/_explorer'
import { Route as Lucro2xRouteImport } from './routes/lucro2x'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ExplorerIndexRouteImport } from './routes/_explorer/index'
import { Route as Lucro2xIndexRouteImport } from './routes/lucro2x.index'
import { Route as Lucro2xCheckoutRouteImport } from './routes/lucro2x.checkout'
import { Route as ApiLucro2xCheckoutRouteImport } from './routes/api/lucro2x/checkout'
import { Route as ApiPublicCountriesRouteImport } from './routes/api/public/countries'
import { Route as ExplorerPaisCca2IndexRouteImport } from './routes/_explorer/pais/$cca2/index'
import { Route as ExplorerPaisCca2CidadeRouteImport } from './routes/_explorer/pais/$cca2/$cidade'

const ExplorerRoute = ExplorerRouteImport.update({
  id: '/_explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const Lucro2xRoute = Lucro2xRouteImport.update({
  id: '/lucro2x',
  path: '/lucro2x',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerIndexRoute = ExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExplorerRoute,
} as any)
const Lucro2xIndexRoute = Lucro2xIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Lucro2xRoute,
} as any)
const Lucro2xCheckoutRoute = Lucro2xCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => Lucro2xRoute,
} as any)
const ApiLucro2xCheckoutRoute = ApiLucro2xCheckoutRouteImport.update({
  id: '/api/lucro2x/checkout',
  path: '/api/lucro2x/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCountriesRoute = ApiPublicCountriesRouteImport.update({
  id: '/api/public/countries',
  path: '/api/public/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerPaisCca2IndexRoute = ExplorerPaisCca2IndexRouteImport.update({
  id: '/pais/$cca2/',
  path: '/pais/$cca2/',
  getParentRoute: () => ExplorerRoute,
} as any)
const ExplorerPaisCca2CidadeRoute = ExplorerPaisCca2CidadeRouteImport.update({
  id: '/pais/$cca2/$cidade',
  path: '/pais/$cca2/$cidade',
  getParentRoute: () => ExplorerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ExplorerIndexRoute
  '/lucro2x': typeof Lucro2xRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lucro2x/checkout': typeof Lucro2xCheckoutRoute
  '/lucro2x/': typeof Lucro2xIndexRoute
  '/api/lucro2x/checkout': typeof ApiLucro2xCheckoutRoute
  '/api/public/countries': typeof ApiPublicCountriesRoute
  '/pais/$cca2/$cidade': typeof ExplorerPaisCca2CidadeRoute
  '/pais/$cca2/': typeof ExplorerPaisCca2IndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lucro2x/checkout': typeof Lucro2xCheckoutRoute
  '/': typeof ExplorerIndexRoute
  '/lucro2x': typeof Lucro2xIndexRoute
  '/api/lucro2x/checkout': typeof ApiLucro2xCheckoutRoute
  '/api/public/countries': typeof ApiPublicCountriesRoute
  '/pais/$cca2/$cidade': typeof ExplorerPaisCca2CidadeRoute
  '/pais/$cca2': typeof ExplorerPaisCca2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_explorer': typeof ExplorerRouteWithChildren
  '/lucro2x': typeof Lucro2xRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/lucro2x/checkout': typeof Lucro2xCheckoutRoute
  '/_explorer/': typeof ExplorerIndexRoute
  '/lucro2x/': typeof Lucro2xIndexRoute
  '/api/lucro2x/checkout': typeof ApiLucro2xCheckoutRoute
  '/api/public/countries': typeof ApiPublicCountriesRoute
  '/_explorer/pais/$cca2/$cidade': typeof ExplorerPaisCca2CidadeRoute
  '/_explorer/pais/$cca2/': typeof ExplorerPaisCca2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lucro2x'
    | '/sitemap.xml'
    | '/lucro2x/checkout'
    | '/lucro2x/'
    | '/api/lucro2x/checkout'
    | '/api/public/countries'
    | '/pais/$cca2/$cidade'
    | '/pais/$cca2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/lucro2x/checkout'
    | '/'
    | '/lucro2x'
    | '/api/lucro2x/checkout'
    | '/api/public/countries'
    | '/pais/$cca2/$cidade'
    | '/pais/$cca2'
  id:
    | '__root__'
    | '/_explorer'
    | '/lucro2x'
    | '/sitemap.xml'
    | '/lucro2x/checkout'
    | '/_explorer/'
    | '/lucro2x/'
    | '/api/lucro2x/checkout'
    | '/api/public/countries'
    | '/_explorer/pais/$cca2/$cidade'
    | '/_explorer/pais/$cca2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExplorerRoute: typeof ExplorerRouteWithChildren
  Lucro2xRoute: typeof Lucro2xRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiLucro2xCheckoutRoute: typeof ApiLucro2xCheckoutRoute
  ApiPublicCountriesRoute: typeof ApiPublicCountriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_explorer': {
      id: '/_explorer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucro2x': {
      id: '/lucro2x'
      path: '/lucro2x'
      fullPath: '/lucro2x'
      preLoaderRoute: typeof Lucro2xRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explorer/': {
      id: '/_explorer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ExplorerIndexRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/lucro2x/': {
      id: '/lucro2x/'
      path: '/'
      fullPath: '/lucro2x/'
      preLoaderRoute: typeof Lucro2xIndexRouteImport
      parentRoute: typeof Lucro2xRoute
    }
    '/lucro2x/checkout': {
      id: '/lucro2x/checkout'
      path: '/checkout'
      fullPath: '/lucro2x/checkout'
      preLoaderRoute: typeof Lucro2xCheckoutRouteImport
      parentRoute: typeof Lucro2xRoute
    }
    '/api/lucro2x/checkout': {
      id: '/api/lucro2x/checkout'
      path: '/api/lucro2x/checkout'
      fullPath: '/api/lucro2x/checkout'
      preLoaderRoute: typeof ApiLucro2xCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/countries': {
      id: '/api/public/countries'
      path: '/api/public/countries'
      fullPath: '/api/public/countries'
      preLoaderRoute: typeof ApiPublicCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explorer/pais/$cca2/': {
      id: '/_explorer/pais/$cca2/'
      path: '/pais/$cca2'
      fullPath: '/pais/$cca2/'
      preLoaderRoute: typeof ExplorerPaisCca2IndexRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/_explorer/pais/$cca2/$cidade': {
      id: '/_explorer/pais/$cca2/$cidade'
      path: '/pais/$cca2/$cidade'
      fullPath: '/pais/$cca2/$cidade'
      preLoaderRoute: typeof ExplorerPaisCca2CidadeRouteImport
      parentRoute: typeof ExplorerRoute
    }
  }
}

interface ExplorerRouteChildren {
  ExplorerIndexRoute: typeof ExplorerIndexRoute
  ExplorerPaisCca2CidadeRoute: typeof ExplorerPaisCca2CidadeRoute
  ExplorerPaisCca2IndexRoute: typeof ExplorerPaisCca2IndexRoute
}

const ExplorerRouteChildren: ExplorerRouteChildren = {
  ExplorerIndexRoute: ExplorerIndexRoute,
  ExplorerPaisCca2CidadeRoute: ExplorerPaisCca2CidadeRoute,
  ExplorerPaisCca2IndexRoute: ExplorerPaisCca2IndexRoute,
}

const ExplorerRouteWithChildren = ExplorerRoute._addFileChildren(
  ExplorerRouteChildren,
)

interface Lucro2xRouteChildren {
  Lucro2xCheckoutRoute: typeof Lucro2xCheckoutRoute
  Lucro2xIndexRoute: typeof Lucro2xIndexRoute
}

const Lucro2xRouteChildren: Lucro2xRouteChildren = {
  Lucro2xCheckoutRoute: Lucro2xCheckoutRoute,
  Lucro2xIndexRoute: Lucro2xIndexRoute,
}

const Lucro2xRouteWithChildren =
  Lucro2xRoute._addFileChildren(Lucro2xRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ExplorerRoute: ExplorerRouteWithChildren,
  Lucro2xRoute: Lucro2xRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiLucro2xCheckoutRoute: ApiLucro2xCheckoutRoute,
  ApiPublicCountriesRoute: ApiPublicCountriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
